security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_MANAGER,ROLE_USER]
        ROLE_SYSADMIN:    [ROLE_ADMIN,ROLE_ADMIN,ROLE_USER]

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
      main:
        pattern: ^/
        form_login:
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
        logout:
          path: fos_user_security_logout
          target: timesheet_hr_homepage
        anonymous: true

      dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

    access_control:
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/registration$, roles: ROLE_ADMIN }
#      - { path: ^/resetting$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, roles: ROLE_ADMIN }
