timesheet_hr_homepage:
    path:     /
    defaults: { _controller: TimesheetHrBundle:Default:index }
    requirements:
        _scheme: http
timesheet_hr_reset:
    path:     /reset
    defaults: { _controller: TimesheetHrBundle:Default:reset }
timesheet_hr_resetpassword:
    path:     /resetpassword/{link}
    defaults: { _controller: TimesheetHrBundle:Default:resetpassword, link: '' }
timesheet_hr_menu:
    path:     /menu
    defaults: { _controller: TimesheetHrBundle:Internal:menu }
timesheet_hr_login:
    path:     /login
    defaults: { _controller: TimesheetHrBundle:Default:login }
#timesheet_hr_registration:
#    path:     /registration
#    defaults: { _controller: TimesheetHrBundle:Default:registration }
timesheet_hr_dashboard:
    path:     /dashboard.{_format}
    defaults: { _controller: TimesheetHrBundle:Default:dashboard, _format: html }
    requirements:
        _format: html
        _scheme: http
timesheet_hr_timesheet:
    path:     /timesheet/{userId}/{timestamp}/{usersearch}
    defaults: { _controller: TimesheetHrBundle:Default:timesheet, userId: '0', timestamp: '0', usersearch: '' }
    requirements:
        _format: html
        _scheme: http
timesheet_hr_autopunch:
    path:     /autopunch/{userId}/{date}
    defaults: { _controller: TimesheetHrBundle:Default:autopunch, userId: '0', date: '' }
    requirements:
        _format: html
        _scheme: http
timesheet_hr_autologout:
    path:     /autologout/{minutes}
    defaults: { _controller: TimesheetHrBundle:Default:autologout, minutes: '' }
    requirements:
        _format: html
        _scheme: http
timesheet_hr_schedule:
    path:     /schedule/{locationId}/{timestamp}
    defaults: { _controller: TimesheetHrBundle:Default:schedule, locationId: '', timestamp: '' }
timesheet_hr_holiday:
    path:     /holiday/{userId}/{timestamp}
    defaults: { _controller: TimesheetHrBundle:Default:holiday, userId: '0', timestamp: '0' }
timesheet_hr_admin:
    path:     /admin/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:admin, action: '', param1: '', param2: '' }
timesheet_hr_configuration:
    path:     /configuration/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:configuration, action: '', param1: '', param2: '' }
timesheet_hr_templates:
    path:     /templates/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:templates, action: '', param1: '', param2: '' }
timesheet_hr_users:
    path:     /users/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:users, action: '', param1: '', param2: '' }
timesheet_hr_messages:
    path:     /messages/{action}/{page}
    defaults: { _controller: TimesheetHrBundle:Default:messages, action: '', page: '' }
timesheet_hr_locations:
    path:     /locations/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:locations, action: '', param1: '', param2: '' }
timesheet_hr_shifts:
    path:     /shifts/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:shifts, action: '', param1: '', param2: '' }
timesheet_hr_weeklyreport:
    path:     /weekly.pdf/{timestamp}/{user}
    defaults: { _controller: TimesheetHrBundle:Default:weeklyreport, timestamp: '', user: '' }
timesheet_hr_monthlyreport:
    path:     /monthly.pdf/{timestamp}/{user}
    defaults: { _controller: TimesheetHrBundle:Default:monthlyreport, timestamp: '', user: '' }
timesheet_hr_weeklylocationreport:
    path:     /weeklylocation.pdf/{timestamp}/{location}/{type}
    defaults: { _controller: TimesheetHrBundle:Default:weeklylocationreport, timestamp: '', location: '', type: '' }
timesheet_hr_sysadmin:
    path:     /sysadmin/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Default:sysadmin, action: '', param1: '', param2: '' }
timesheet_hr_forgotpassword:
    path:     /forgotpassword
    defaults: { _controller: TimesheetHrBundle:Default:forgotpassword }
timesheet_hr_userphotos:
    path:     /userphotos/{action}/{id}
    defaults: { _controller: TimesheetHrBundle:Default:userphotos, action: '', id: '' }
timesheet_hr_timesheetreport:
    path:     /reports/timesheet/{timestamp}/{userid}
    defaults: { _controller: TimesheetHrBundle:Default:timesheetreport, timestamp: '', userid: '' }
timesheet_hr_timesheetreportsummary:
    path:     /reports/timesheetsummary/{filetype}/{timestamp}/{userid}
    defaults: { _controller: TimesheetHrBundle:Default:timesheetreportsummary, timestamp: '', userid: '', filetype: 'pdf' }
timesheet_hr_latenessreport:
    path:     /reports/lateness/{filetype}/{timestamp}/{userid}/{holidays}
    defaults: { _controller: TimesheetHrBundle:Default:latenessreport, timestamp: '', userid: '', filetype: 'pdf', holidays: '0' }
timesheet_hr_sageexport:
    path:     /reports/sage/export/{filetype}
    defaults: { _controller: TimesheetHrBundle:Default:sageexport, filetype: 'csv' }
timesheet_hr_sageimport:
    path:     /reports/sage/import
    defaults: { _controller: TimesheetHrBundle:Default:sageimport }

timesheet_mobile_index:
    path:     /mobile
    defaults: { _controller: TimesheetHrBundle:Mobile:index }
timesheet_mobile_manifest:
    path:     /mobile/manifest
    defaults: { _controller: TimesheetHrBundle:Mobile:manifest }
timesheet_mobile_punch:
    path:     /mobile/punch/{auth}
    defaults: { _controller: TimesheetHrBundle:Mobile:punch, auth: '' }


timesheet_update_attendance:
    path:     /update/attendance
    defaults: { _controller: TimesheetHrBundle:Default:updateattendance }


residents_hr_dashboard:
    path:     /residentshome
    defaults: { _controller: TimesheetHrBundle:Residents:index }
residents_hr_list:
    path:     /residents/{action}/{id}
    defaults: { _controller: TimesheetHrBundle:Residents:residentlist, action: '', id: '' }
residents_hr_move:
    path:     /residentmove/{id}
    defaults: { _controller: TimesheetHrBundle:Residents:residentmove, id: '' }
residents_hr_residentcontacts:
    path:     /residentcontacts/{action}/{residentid}/{contactid}
    defaults: { _controller: TimesheetHrBundle:Residents:residentcontacts, action: '', residentid: '', contactid: '' }
residents_hr_residentphotos:
    path:     /residentphotos/{action}/{id}
    defaults: { _controller: TimesheetHrBundle:Residents:residentphotos, action: '', id: '' }
residents_hr_rooms:
    path:     /rooms/{action}/{param1}/{param2}
    defaults: { _controller: TimesheetHrBundle:Residents:rooms, action: '', param1: '', param2: '' }


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile


timesheet_internal_groupmenu:
    path:     /groupmenu/{domainId}
    defaults: { _controller: TimesheetHrBundle:Internal:groupmenu, domainId: '' }
timesheet_internal_locationmenu:
    path:     /locationmenu/{base}
    defaults: { _controller: TimesheetHrBundle:Internal:locationmenu, base: '' }
timesheet_internal_qualificationmenu:
    path:     /qualificationmenu
    defaults: { _controller: TimesheetHrBundle:Internal:qualificationmenu }
timesheet_internal_usermenu:
    path:     /usermenu/{base}
    defaults: { _controller: TimesheetHrBundle:Internal:usermenu, base: '' }
timesheet_internal_userqualificationmenu:
    path:     /userqualificationmenu
    defaults: { _controller: TimesheetHrBundle:Internal:userqualificationmenu }


timesheet_ajax_addpunch:
    path:     /ajax/addpunch/{type}/{timestamp}
    defaults: { _controller: TimesheetHrBundle:Ajax:addpunch, type: '', timestamp: '0' }
timesheet_ajax_addrequest:
    path:     /ajax/addrequest
    defaults: { _controller: TimesheetHrBundle:Ajax:addrequest }
timesheet_ajax_allocation:
    path:     /ajax/allocation/{date}/{locationId}/{shiftId}
    defaults: { _controller: TimesheetHrBundle:Ajax:allocation, date: '', locationId: '', shiftId: '' }
timesheet_ajax_approvedeny:
    path:     /ajax/approvedeny
    defaults: { _controller: TimesheetHrBundle:Ajax:approvedeny }
timesheet_ajax_getmessage:
    path:     /ajax/getmessage/{id}
    defaults: { _controller: TimesheetHrBundle:Ajax:getmessage, id: '' }
timesheet_ajax_handleholidayrequest:
    path:     /ajax/handleholidayrequest
    defaults: { _controller: TimesheetHrBundle:Ajax:handleholidayrequest }
timesheet_ajax_handleswaprequest:
    path:     /ajax/handleswaprequest
    defaults: { _controller: TimesheetHrBundle:Ajax:handleswaprequest }
timesheet_ajax_holiday:
    path:     /ajax/holiday
    defaults: { _controller: TimesheetHrBundle:Ajax:holiday }
timesheet_ajax_holidaylist:
    path:     /ajax/holidayList/{userId}/{timestamp}/{func}
    defaults: { _controller: TimesheetHrBundle:Ajax:holidayList, userId: '0', timestamp: '0', func: '' }
timesheet_ajax_photo:
    path:     /ajax/photo
    defaults: { _controller: TimesheetHrBundle:Ajax:photo }
timesheet_ajax_schedule:
    path:     /ajax/schedule
    defaults: { _controller: TimesheetHrBundle:Ajax:schedule }
timesheet_ajax_schedulelist:
    path:     /ajax/scheduleList/{locationId}/{timestamp}/{func}/{usersearch}/{groupsearch}/{qualificationsearch}/{base}
    defaults: { _controller: TimesheetHrBundle:Ajax:scheduleList, locationId: '0', timestamp: '0', func: '', usersearch: '', groupsearch: '', qualificationsearch: '', base: '' }
timesheet_ajax_shiftday:
    path:     /ajax/shiftday/{dayid}
    defaults: { _controller: TimesheetHrBundle:Ajax:shiftday, dayid: '' }
timesheet_ajax_showdailyproblems:
    path:     /ajax/showdailyproblems
    defaults: { _controller: TimesheetHrBundle:Ajax:showdailyproblems }
timesheet_ajax_staffstatus:
    path:     /ajax/staffstatus/{userid}
    defaults: { _controller: TimesheetHrBundle:Ajax:staffstatus, userid: '' }
timesheet_ajax_showrequests:
    path:     /ajax/showrequests/{userid}
    defaults: { _controller: TimesheetHrBundle:Ajax:showrequests, userid: '' }
timesheet_ajax_swapapprovedeny:
    path:     /ajax/swapapprovedeny
    defaults: { _controller: TimesheetHrBundle:Ajax:swapapprovedeny }
timesheet_ajax_swaprequest:
    path:     /ajax/swaprequest
    defaults: { _controller: TimesheetHrBundle:Ajax:swaprequest }
timesheet_ajax_sysadmin:
    path:     /ajax/sysadmin
    defaults: { _controller: TimesheetHrBundle:Ajax:sysadmin }
timesheet_ajax_timesheetcheck:
    path:     /ajax/timesheetcheck
    defaults: { _controller: TimesheetHrBundle:Ajax:timesheetcheck }
timesheet_ajax_timesheetlist:
    path:     /ajax/timesheetList/{userId}/{timestamp}/{func}/{usersearch}
    defaults: { _controller: TimesheetHrBundle:Ajax:timesheetList, userId: '0', timestamp: '0', func: '', usersearch: '' }
timesheet_ajax_userinfo:
    path:     /ajax/userinfo/{id}
    defaults: { _controller: TimesheetHrBundle:Ajax:userinfo, id: '' }
timesheet_ajax_userlist:
    path:     /ajax/userlist
    defaults: { _controller: TimesheetHrBundle:Ajax:userlist }
timesheet_ajax_userphoto:
    path:     /ajax/userphoto
    defaults: { _controller: TimesheetHrBundle:Ajax:userphoto }
timesheet_ajax_usershift:
    path:     /ajax/usershift/{userid}
    defaults: { _controller: TimesheetHrBundle:Ajax:usershift, userid: '' }
timesheet_ajax_updatereader:
    path:     /ajax/updatereader/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:updatereader, readerid: '' }
timesheet_ajax_syncreaderusers:
    path:     /ajax/syncreaderusers/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:syncreaderusers, readerid: '' }
timesheet_ajax_resetreader:
    path:     /ajax/resetreader/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:resetreader, readerid: '' }
timesheet_ajax_readeradminpwd:
    path:     /ajax/readeradminpwd/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:readeradminpwd, readerid: '' }
timesheet_ajax_downloadattn:
    path:     /ajax/downloadattn/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:downloadattn, readerid: '' }
timesheet_ajax_showallattn:
    path:     /ajax/showallattn/{readerid}
    defaults: { _controller: TimesheetHrBundle:Ajax:showallattn, readerid: '' }
timesheet_ajax_savereaderallocation:
    path:     /ajax/savereaderallocation
    defaults: { _controller: TimesheetHrBundle:Ajax:savereaderallocation }
timesheet_ajax_position:
    path:     /ajax/position
    defaults: { _controller: TimesheetHrBundle:Ajax:position }

timesheet_ajax_residenthistory:
    path:     /ajax/residenthistory
    defaults: { _controller: TimesheetHrBundle:Ajax:residenthistory }
timesheet_ajax_residentphoto:
    path:     /ajax/residentphoto
    defaults: { _controller: TimesheetHrBundle:Ajax:residentphoto }
