parameters:

services:
    timesheet.hr.functions:
        class: Timesheet\Bundle\HrBundle\Service\Functions
        arguments: [@doctrine, @request_stack]
        calls:
          - [ setContainer, [ @service_container ] ]
    timesheet.default.controller:
        class: Timesheet\Bundle\HrBundle\Controller\DefaultController
    timesheet.residents.controller:
        class: Timesheet\Bundle\HrBundle\Controller\ResidentsController
    request_injector:
        class: RequestInjector
        public: false
        arguments: ['@service_container']
    
    timesheet_user.login:
        class: Timesheet\Bundle\HrBundle\EventListener\LoginListener
        argument: [@router]
        tage:
          - { name: kernel.event_subscriber }

    timesheet_user.register:
        class: Timesheet\Bundle\HrBundle\EventListener\RegisterListener
        argument: [@router]
        tage:
          - { name: kernel.event_subscriber }          
          
    timesheet_user.password_resetting:
        class: Timesheet\Bundle\HrBundle\EventListener\PasswordResettingListener
        argument: [@router]
        tage:
          - { name: kernel.event_subscriber }          

    timesheet.twig_extension:
        class: Timesheet\Bundle\HrBundle\Twig\Extension\LocaleExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }
          
    userbundle_service:
        class: FOS\UserBundle\Doctrine\UserManager
        arguments: [@fos_user.user_manager]
        
    timesheet.exception_listener:
        class: Timesheet\Bundle\HrBundle\EventListener\ExceptionListener
        arguments: [@router]
        tags:
          - { name: kernel.event_listener, event: kernel.exception }
    fos_user.doctrine_registry:
        alias: doctrine
        